kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
  event:
    - deployment
    - push

steps:

  - name: build
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker build -t memes-backend-image .

  - name: stop-previous
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stop memes-app-backend || true
      - docker rm memes-app-backend || true

  - name: deploy
    image: docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker run -d -p 39004:8080 --network=memes-network --name memes-app-backend memes-backend-image

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock