server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: memesback
  config:
    import: configserver:http://config-server-dev:8888

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: ${DATABASE.URL}
    username: ${DATABASE.USERNAME}
    password: ${DATABASE.PASSWD}
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

minio:
  endpoint: ${MINIO.URL}
  secret-key: ${MINIO.SECRET_KEY}
  access-key: ${MINIO.ACCESS_KEY}
  bucket-name: ${MINIO.BUCKET}

giphy:
  active: ${GIPHY.ACTIVE}
  url: https://api.giphy.com/v1/gifs/search
  api-key: ${GIPHY.API-KEY}

users:
  admin:
    username: ${USERS.ADMIN.username}
    password: ${USERS.ADMIN.password}

springdoc:
  cache:
    disabled: true