name: Build and Deploy to Master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          CR_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }} .
          docker tag ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.K3S_TOKEN }}" | base64 --decode > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig

      - name: Deploy using Helm
        run: |
          helm upgrade -i memes-service-${{ github.ref_name }} helm \
            --set image.tag=${{ github.ref_name }}-${{ github.run_number }} \
            -f helm/values.${{ github.ref_name }}.yaml \
            -n ${{ vars.KUBE_NS }}