name: Build and Deploy to Master

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_ROBOT_NAME }}
          password: ${{ secrets.REGISTRY_ROBOT_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_PATH }}/${{ vars.SERVICE_NAME }}:${{ github.ref_name }}-${{ github.run_number }} .
          docker tag ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_PATH }}/${{ vars.SERVICE_NAME }}:${{ github.ref_name }}-${{ github.run_number }} ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_PATH }}/${{ vars.SERVICE_NAME }}:${{ github.ref_name }}-latest
          docker push ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_PATH }}/${{ vars.SERVICE_NAME }}:${{ github.ref_name }}-${{ github.run_number }}
          docker push ${{ vars.REGISTRY_URL }}/${{ vars.REGISTRY_PATH }}/${{ vars.SERVICE_NAME }}:${{ github.ref_name }}-latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.K3S_TOKEN }}" | base64 --decode > /tmp/kubeconfig
          export KUBECONFIG=/tmp/kubeconfig

      - name: Deploy using Helm
        run: |
          helm upgrade -i memes-service-${{ github.ref_name }} helm \
            --set image.tag=${{ github.ref_name }}-${{ github.run_number }} \
            -f helm/values.${{ github.ref_name }}.yaml \
            -n $KUBE_NS